name: lx/lx-demo

autoload:
  psr-4:
    lx\demo\: ''
  classmap: [
    exemples/02_app/07_example/backend
    exemples/04_js/08_tools/02_synchronizer/backend
    exemples/roulette/backend
  ]

service:
  class: lx\demo\Service
  router:
    type: map
    routes:
      /: {plugin: _main}
  plugins: ''
  models: exemples/roulette/model
  aliases:
    viewTools: tools/viewBuilder
